In [2]:
import sys, time
import pandas as pd
import datetime as dt
from IPython.display import display

In [6]:
path = 'flightlist_20191201_20191231.csv'

In [7]:
df = pd.read_csv(path)
df.head()

,callsign,number,icao24,registration,typecode,origin,destination,firstseen,lastseen,day,latitude_1,longitude_1,altitude_1,latitude_2,longitude_2,altitude_2
0,THY183,NaN,4ba9c2,TC-JNB,A332,NaN,LTBW,2019-11-30 00:11:15+00:00,2019-12-01 08:12:17+00:00,2019-12-01 00:00:00+00:00,41.181879,28.832932,914.4,41.151666,28.709585,701.04
1,HVN19,VN19,888167,NaN,NaN,YMML,LFPG,2019-11-30 00:57:39+00:00,2019-12-01 05:10:22+00:00,2019-12-01 00:00:00+00:00,-37.680222,144.840010,0.0,48.993816,2.582439,NaN
2,CES201,NaN,780b33,B-5930,A332,YMML,EGKK,2019-11-30 01:19:12+00:00,2019-12-01 05:37:59+00:00,2019-12-01 00:00:00+00:00,-37.685989,144.841296,0.0,51.144150,-0.219430,60.96
3,KQA210,KQ210,04c148,5Y-CYB,B738,FAOR,VABB,2019-11-30 01:46:07+00:00,2019-12-01 10:43:44+00:00,2019-12-01 00:00:00+00:00,-26.116196,28.243829,1524.0,19.088745,72.869917,30.48
4,MAU851,NaN,06002a,3B-NBL,A332,VABB,FAOR,2019-11-30 01:46:50+00:00,2019-12-01 09:29:13+00:00,2019-12-01 00:00:00+00:00,19.088605,72.860229,-304.8,-26.152771,28.251861,1569.72

In [3]:
FILE_NAME = "output.gml"

In [4]:
authors = pd.read_csv('authors.csv', sep=' ')
occurrence = pd.read_csv('occurrence.csv', sep=' ')

In [5]:
#Utility functions
def progress(v):
    v = str(v)
    sys.stdout.flush()
    sys.stdout.write('\r')
    sys.stdout.flush()
    sys.stdout.write(v)

In [6]:
a = authors.assign(CO_AUTHOR_ID=authors['AUTHOR_ID']).assign(CO_AUTHOR_NAME=authors['AUTHOR_NAME'])
b = occurrence.merge(authors, how='inner', on='AUTHOR_ID')
#.merge(a, how='inner', on='AUTHOR_ID')
df = b.merge(a, how='inner', on='CO_AUTHOR_ID') \
    .sort_values(by='AUTHOR_ID_x') \
    .drop('AUTHOR_ID_y',1) \
    .drop('AUTHOR_NAME_y',1)
df.columns = ['AUTHOR_ID', 'CO-AUTHOR_ID', 'NO_OF_BOOKS', 'AUTHOR', 'CO-AUTHOR']
df

       AUTHOR_ID  CO-AUTHOR_ID  NO_OF_BOOKS          AUTHOR         CO-AUTHOR
0              1           190            7  RADZIHOVSKY, L          TONER, J
66             1          2281            1  RADZIHOVSKY, L           FREY, E
93             1          3896            1  RADZIHOVSKY, L      GINZBURG, VV
101            1          3897            2  RADZIHOVSKY, L         CLARK, NA
110            1         12347            1  RADZIHOVSKY, L       JACOBSEN, B
113            1         12348            1  RADZIHOVSKY, L       SAUNDERS, K
116            1         12700            1  RADZIHOVSKY, L          LINK, DR
123            1         12701            1  RADZIHOVSKY, L         NATALE, G
130            1         12702            1  RADZIHOVSKY, L     MACLENNAN, JE
137            1         12703            1  RADZIHOVSKY, L          WALSH, M
144            1         12704            1  RADZIHOVSKY, L         KEAST, SS
151            1         12705            1  RADZIHOVSKY, L       NEUBERT, ME
55             1          1075            3  RADZIHOVSKY, L     MARCHETTI, MC
35             1           562            2  RADZIHOVSKY, L        NELSON, DR
11             1           201            3  RADZIHOVSKY, L        BALENTS, L
159            2          1237            2    FRISCHAT, SD          DORON, E
158            2             3            1    FRISCHAT, SD           KUHN, R
160            3             2            1         KUHN, R      FRISCHAT, SD
311            4         10757            9  BEENAKKER, CWJ          PATRA, M
215            4           891            2  BEENAKKER, CWJ       LEYRONAS, X
219            4          1785            1  BEENAKKER, CWJ       BUTTIKER, M
243            4          2212            5  BEENAKKER, CWJ       LANGEN, SAV
200            4           722            1  BEENAKKER, CWJ          FRAHM, K
255            4          2264            1  BEENAKKER, CWJ       BLANTER, YM
196            4             7            4  BEENAKKER, CWJ        JONG, MJMD
268            4          2876            9  BEENAKKER, CWJ      SCHOMERUS, H
290            4          3232            5  BEENAKKER, CWJ  MISIRPASHAEV, TS
306            4          8994            2  BEENAKKER, CWJ      TWORZYDLO, J
293            4          3478            7  BEENAKKER, CWJ         FRAHM, KM
162            4             5            5  BEENAKKER, CWJ        MELSEN, JA
...          ...           ...          ...             ...               ...
67404      16718          8621            1         RENZ, F          JAKOB, G
87838      16718         16716            1         RENZ, F         TREMEL, W
87566      16719         13396            1     GUETLICH, P         RITTER, C
83218      16719         13170            1     GUETLICH, P     WESTERBURG, W
87855      16719         16718            1     GUETLICH, P           RENZ, F
87847      16719         16717            1     GUETLICH, P        WALDECK, M
67405      16719          8621            1     GUETLICH, P          JAKOB, G
87839      16719         16716            1     GUETLICH, P         TREMEL, W
87831      16719         16715            1     GUETLICH, P         FELSER, C
87823      16719         16714            1     GUETLICH, P           LANG, O
80930      16720         11553            1    HAEUSSLER, R    LOEHNEYSEN, HV
51427      16720         15834            1    HAEUSSLER, R         SCHEER, E
91849      16720         16721            1    HAEUSSLER, R         WEBER, HB
51428      16721         15834            1       WEBER, HB         SCHEER, E
80931      16721         11553            1       WEBER, HB    LOEHNEYSEN, HV
91846      16721         16720            1       WEBER, HB      HAEUSSLER, R
74577      16723         14983            1       LEUNG, MA          CARR, LD
68050      16723          4256            1       LEUNG, MA     REINHARDT, WP
41242      16724          8897            1     CORNISH, SL        WIEMAN, CE
80425      16724         16725            1     CORNISH, SL      CLAUSSEN, NR
80429      16724         16726            1     CORNISH, SL       ROBERTS, JL
41176      16724          5350            1     CORNISH, SL       CORNELL, EA
41177      16725          5350            1    CLAUSSEN, NR       CORNELL, EA
80430      16725         16726            1    CLAUSSEN, NR       ROBERTS, JL
41243      16725          8897            1    CLAUSSEN, NR        WIEMAN, CE
80421      16725         16724            1    CLAUSSEN, NR       CORNISH, SL
41244      16726          8897            1     ROBERTS, JL        WIEMAN, CE
80426      16726         16725            1     ROBERTS, JL      CLAUSSEN, NR
80422      16726         16724            1     ROBERTS, JL       CORNISH, SL
41178      16726          5350            1     ROBERTS, JL       CORNELL, EA

[95188 rows x 5 columns]

In [10]:
f = open(FILE_NAME, "w")
#helpers
s = " "
ss = s+s
sss = s+s+s
ssss = s+s+s+s
nl = "\n"

#loop helpers
added = []
ind = 0

#Root node
f.write("graph"+nl)
f.write("["+nl)

#Write an edge
def write_edge(r):
    f.write( ss + "edge" + nl)
    f.write( ss + "[" + nl)
    f.write( ssss + "source" + s + '"' + str(r['AUTHOR_ID']) + '"' + nl)
    f.write( ssss + "target" + s + '"' + str(r['CO-AUTHOR_ID']) + '"' + nl)
    f.write( ssss + "value" + s + str(r['NO_OF_BOOKS']) + '"' + nl)
    f.write( ss + "]"+ nl)

#Write a node
def write_node(r):
    f.write( ss + "node" + nl)
    f.write( ss + "[" + nl)
    f.write( ssss + "id" + s + '"' + str(r['AUTHOR_ID']) + '"' + nl)
    f.write( ssss + "label" + s + '"' + str(r['AUTHOR']) + '"' + nl)
    f.write( ss + "]"+ nl)

#Generate nodes
for i, r in df.iterrows():
    #increment, as index not reliable
    ind += 1
    #Check for duplicates
    if (r['AUTHOR_ID'] not in added):
        #Add to list
        added.append(r['AUTHOR_ID'])
        write_node(r)
    #print the progress    
    progress(ind)

print(nl+"Printing nodes over")

#flush index
ind = 0    
#Generate edges    
for i, r in df.iterrows():
    #increment, as index not reliable
    ind += 1
    if(r['AUTHOR_ID'] < r['CO-AUTHOR_ID']):
        write_edge(r)
    #print the progress            
    progress(ind)

print(nl+"Printing nodes and edges over")

#closing node
f.write("]"+nl)
f.close()

95188
Printing nodes over
95188
Printing nodes and edges over